### ISSUE TITLE
pnpm issue not fixed

### ISSUE THREAD

**Issue by efrazier** [directus-community/agency-os#60] opened 2023-12-27 23:15 UTC
https://github.com/pnpm/pnpm/issues/946

I ran into this right away on my `pnpm i`  It doesn't seem like there is much of an issue just running npm.  But I wondered why use a tool that clearly isn't well maintained. Note the "6 years later" comment.

**Comment by efrazier** [comment] 2023-12-27 23:30
![image](https://github.com/directus-community/agency-os/assets/3696386/b2fbcbcf-4ad8-406a-a259-7d2d5f303c30)
So this failed as well.  I think the memory needed to install these packages is out of hand.  
![image](https://github.com/directus-community/agency-os/assets/3696386/399709ce-8444-4fbc-b1ff-c2ee0397a095)

This IS because I have a micro instance on AWS that is setup with no swap, somehow. Bad on me for sure. But I still wouldn't have expected this level of brokenness over an npm install for what is basically, building a website.  Will try both again with more memory and actual swap.

**Comment by efrazier** [comment] 2023-12-27 23:37
So an AWS small instance made a big difference.  I ran `pnpm i` but still ran into this wall. 
![image](https://github.com/directus-community/agency-os/assets/3696386/98e22520-8b10-4bd3-a76b-eb0a65b11916)

**Comment by omgitsjan** [comment] 2023-12-29 15:53
So first of all I don't think pnpm isn't well maintend. pnpm has a lot of benefits and is used widely, though, like any large project, it's not without its specific issues. These problems sound more like an environment error with AWS and pnpm less than something we can fix here in this repo. On my side, Vercel is doing fine, same with when I build it on Mac or on my Windows pc. I don't have an AWS Instance, so I personally can't reproduce this.

I don't think the deployment process hasn't a lot to do with AgencyOS more with nuxt as such. I suggest raising an issue on the Nuxt or pnpm repositories, or contributing to the discussion in the issue you mentioned, especially since this seems to involve specific versioning details and a deeper understanding of pnpm.

Can you specify which version of pnpm you're using? Additionally, you mentioned memory-related issues, but you didn't provide any specific details about your system's memory specifications.

According to the issue you referenced (https://github.com/pnpm/pnpm/issues/946#issuecomment-1710554299), it appears to be a version-related issue that was resolved by updating to Node 20.5."

**Comment by bryantgillespie** [comment] 2024-01-07 19:06
closing because this is not an AgencyOS issue

**Closed by bryantgillespie** 2024-01-07 19:06 UTC
